/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

func solution() -> Int {
    var result = 2
    var a = 1
    var b = 2
    
    while result <= 4_000_000 {
        let c = b
        b = a + b
        a = c
        if b % 2 == 0 {
            result += b
        }
    }
    
    return result
}

solution()
